# Generated by Django 3.1 on 2020-12-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('identificación', models.IntegerField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('teléfono', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('email', models.EmailField(blank=True, help_text='Ingrese aqui su correo electronico si le gustaria recibir promociones y ofertas', max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='habitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('tipo_habitacion', models.CharField(choices=[('IND', 'Individual'), ('DI', 'Doble de Uso Individual'), ('HD', 'Habitación Doble'), ('CS', 'Con cama Supletoria'), ('HT', 'Habitación Triple'), ('JS', 'Junior Suite'), ('SUI', 'Suite'), ('SN', 'Suit Nupcial')], default='IND', max_length=3)),
                ('precio', models.IntegerField(default=0)),
                ('cupo', models.BooleanField(default=True)),
                ('nro_habitacion', models.IntegerField(max_length=3)),
                ('caracteristicas', models.TextField(blank=True, help_text='Ingresa la descripción de la habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='reservas',
            fields=[
                ('cod_reserva', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('cant_adultos', models.IntegerField()),
                ('cant_niños', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.clientes', unique=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.habitaciones', unique=True)),
            ],
        ),
    ]
