# Generated by Django 3.1 on 2020-12-21 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='habitaciones',
            options={'verbose_name': 'habitación', 'verbose_name_plural': 'habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='reservas',
            options={'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
        migrations.AddField(
            model_name='clientes',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
