# Generated by Django 3.1 on 2020-12-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20201221_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitaciones',
            name='tipo_habitacion',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('DOBLE DE USO INDIVIDUAL', 'Doble de Uso Individual'), ('DOBLE', 'Habitación Doble'), ('CON CAMA SUPLETORIA', 'Con cama Supletoria'), ('TRIPLE', 'Habitación Triple'), ('JUNIOR SUITE', 'Junior Suite'), ('SUITE', 'Suite'), ('SUITE NUPCIAL', 'Suit Nupcial')], default='INDIVIDUAL', max_length=25),
        ),
    ]
