# Generated by Django 3.1 on 2021-02-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20210208_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitaciones',
            name='tipo_habitacion',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('DOBLE DE USO INDIVIDUAL', 'Doble de Uso Individual'), ('DOBLE', 'Habitación Doble'), ('CON CAMA SUPLETORIA', 'Con cama Supletoria'), ('TRIPLE', 'Habitación Triple'), ('JUNIOR SUITE', 'Junior Suite'), ('SUITE', 'Suite'), ('SUITE NUPCIAL', 'Suit Nupcial')], max_length=25),
        ),
    ]
