# Generated by Django 3.1 on 2021-02-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20210210_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitaciones',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='cliente',
        ),
        migrations.AddField(
            model_name='reservas',
            name='correo',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='reservas',
            name='mensaje',
            field=models.TextField(blank=True, help_text='Escriba aqui si tiene alguna petición especial'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='nombre',
            field=models.CharField(default='Nombre Completo', max_length=40),
        ),
        migrations.AddField(
            model_name='reservas',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='habitaciones',
            name='codigo',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='cod_reserva',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
