# Generated by Django 3.1 on 2021-02-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20210222_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitaciones',
            name='codigo',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='cod_reserva',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
