# Generated by Django 3.1 on 2021-02-22 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20210222_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.habitaciones'),
        ),
    ]
