# Generated by Django 3.1 on 2021-02-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_auto_20210222_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitaciones',
            name='caracteristicas',
            field=models.TextField(blank=True, help_text='Descripción de la habitacion'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='cant_niños',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre Completo', max_length=40),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
