# Generated by Django 3.1 on 2021-02-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20210222_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='correo',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
