# Generated by Django 3.1 on 2021-02-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_auto_20210222_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='cant_adultos',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='cant_niños',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='fecha_entrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='fecha_salida',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='nombre',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
